-- ============================================================
--  36 — one post, on its own page.
--
--  Notifications used to drop you on the feed and leave you to find
--  the post yourself. Fine when you have three posts; useless at
--  three hundred, which is the point at which notifications start
--  mattering.
--
--  This returns exactly the same columns as get_feed, so the page can
--  render the identical PostCard — likes, media, session roster, join
--  button and all — rather than a cut-down copy that slowly drifts
--  away from the real thing.
--
--  Generated by transforming get_feed rather than retyping it: the
--  body below is that function with the paging, scope and game
--  filters removed and a single id put in their place.
--
--  Run in the Supabase SQL Editor, after 35.
-- ============================================================

create or replace function public.get_post(want_id bigint)
returns table (
  id            bigint,
  body          text,
  created_at    timestamptz,
  author_id     uuid,
  username      text,
  display_name  text,
  avatar_url    text,
  avatar_preset text,
  game_id       bigint,
  game_name     text,
  game_cover    text,
  likes         bigint,
  liked_by_me   boolean,
  mine          boolean,
  kind          text,
  starts_at     timestamptz,
  slots         smallint,
  taken         bigint,
  i_joined      boolean,
  players       jsonb,
  media         jsonb
)
language sql
security invoker
set search_path = public
stable
as $$
  select
    p.id,
    p.body,
    p.created_at,
    p.author_id,
    a.username,
    a.display_name,
    a.avatar_url,
    a.avatar_preset,
    p.game_id,
    g.name,
    g.cover_url,
    coalesce(l.count, 0),
    exists (
      select 1 from post_likes pl
      where pl.post_id = p.id and pl.user_id = auth.uid()
    ),
    p.author_id = auth.uid(),
    p.kind,
    p.starts_at,
    p.slots,
    coalesce(s.taken, 0),
    exists (
      select 1 from session_players sp
      where sp.post_id = p.id and sp.user_id = auth.uid()
    ),
    coalesce(s.players, '[]'::jsonb),
    coalesce(m.media, '[]'::jsonb)
  from posts p
  join profiles a on a.id = p.author_id
  left join games g on g.id = p.game_id
  left join lateral (
    select count(*) as count from post_likes where post_id = p.id
  ) l on true
  left join lateral (
    select
      count(*) as taken,
      jsonb_agg(
        jsonb_build_object(
          'user_id', pr.id,
          'username', pr.username,
          'display_name', pr.display_name,
          'avatar_url', pr.avatar_url,
          'avatar_preset', pr.avatar_preset,
          'is_host', pr.id = p.author_id
        )
        order by sp.joined_at
      ) as players
    from session_players sp
    join profiles pr on pr.id = sp.user_id
    where sp.post_id = p.id
  ) s on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'kind',   pm.kind,
        'url',    pm.url,
        'width',  pm.width,
        'height', pm.height,
        'alt',    pm.alt
      )
      order by pm.position
    ) as media
    from post_media pm
    where pm.post_id = p.id
  ) m on true
  -- One post, by id.
  --
  -- The feed's scope filter is deliberately NOT carried over. A link
  -- to a post is something you were handed — a notification, a shared
  -- URL — and "everyone" is already the feed's default, so filtering
  -- by friendship here would mean a tag from a friend-of-a-friend
  -- opened an empty page. Blocking still applies: a post from someone
  -- you blocked stays unreachable however you arrived at it.
  where p.id = want_id
    and not public.is_blocked(p.author_id);
$$;

grant execute on function public.get_post(bigint) to authenticated;

-- ============================================================
--  Done.
-- ============================================================
